namespace Prototype.Common {
    using System;

    /// <summary>
    ///   Specifies that the property this attribute is applied to is generated by the application
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
    public sealed class ApplicationGeneratedAttribute : Attribute {
    }
}